# Generated by Django 5.1.1 on 2025-04-30 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 1, 1, 17, 53, 127099), verbose_name='Добавлено'),
            preserve_default=False,
        ),
    ]
